name: Jekyll Site CI

on:
  push:
    branches:
      - master  # 触发事件为推送到 master 分支
  pull_request:
    branches:
      - master  # 针对 master 分支的拉取请求


jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'  # 设置 Ruby 版本

      - name: Install dependencies
        run: |
          gem install bundler -v 2.6.5  # 安装特定版本的 Bundler
          echo "Bundler installed successfully."
          bundle clean --force
          bundle install --force  # 强制重新安装依赖
          echo "Dependencies installed successfully."

      - name: Build the site
        run: |
          bundle exec jekyll build || { echo 'Build failed'; exit 1; }  # 构建 Jekyll 网站
          echo "Site built successfully."

      - name: Deploy
        run: |
          echo "Deploying the site..."  # 在此处添加实际的部署步骤
          - name: Install dependencies

